import type { InventoryCatalog } from "@/types/admin";
import type { Product } from "@/types";

const PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "premium-leather-seat-covers",
    name: "Premium Leather Seat Covers",
    shortDescription: "Custom-fit leather covers for all major car models",
    description: "Transform your car interior with our premium leather seat covers. Available in multiple quality grades from economy LR9 to scratchless premium material.",
    category: "seat-covers",
    basePrice: 15000,
    images: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80",
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&q=80",
    ],
    badge: "Hot",
    isSeatCover: true,
    isFeatured: true,
    inStock: true,
    relatedSlugs: ["7d-floor-mats-premium", "ambient-led-lights", "leather-key-cover-set"],
  },
  {
    id: "2",
    slug: "7d-floor-mats-premium",
    name: "7D Floor Mats Premium Set",
    shortDescription: "Full coverage 7D mats with premium finish",
    description: "Premium 7D floor mats designed for complete floor protection.",
    category: "floor-mats",
    basePrice: 4500,
    images: [
      "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
    ],
    badge: "Best Seller",
    isSeatCover: false,
    isFeatured: true,
    inStock: true,
    relatedSlugs: ["tp-full-protection-mats", "premium-leather-seat-covers"],
  },
  {
    id: "3",
    slug: "led-headlight-projector",
    name: "LED Headlight Projector Kit",
    shortDescription: "Crystal-clear projector headlights with LED technology",
    description: "Upgrade your visibility with our premium LED projector headlight kit.",
    category: "led-lights",
    basePrice: 8500,
    images: [
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80",
      "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80",
    ],
    badge: "Hot",
    isSeatCover: false,
    isFeatured: true,
    inStock: true,
    relatedSlugs: ["ambient-led-lights", "fog-lights-led"],
  },
  {
    id: "4",
    slug: "tp-full-protection-mats",
    name: "TP Full Protection Mats",
    shortDescription: "Complete trunk & floor protection system",
    description: "Total Protection mats provide 360° floor and trunk coverage.",
    category: "floor-mats",
    basePrice: 6200,
    images: [
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&q=80",
    ],
    badge: "Limited Stock",
    isSeatCover: false,
    isFeatured: true,
    inStock: true,
    relatedSlugs: ["7d-floor-mats-premium"],
  },
  {
    id: "5",
    slug: "ambient-led-lights",
    name: "Ambient Interior LED Lights",
    shortDescription: "RGB ambient lighting for luxury cabin feel",
    description: "Create a premium showroom atmosphere inside your car.",
    category: "led-lights",
    basePrice: 3200,
    images: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
    ],
    badge: "Best Seller",
    isSeatCover: false,
    isFeatured: true,
    inStock: true,
    relatedSlugs: ["led-headlight-projector"],
  },
  {
    id: "6",
    slug: "universal-mobile-holder",
    name: "Universal Mobile Holder",
    shortDescription: "Sturdy dashboard mount with 360° rotation",
    description: "Keep your phone secure while driving.",
    category: "mobile-holders",
    basePrice: 1200,
    images: [
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80",
    ],
    badge: "Hot",
    isSeatCover: false,
    isFeatured: true,
    inStock: true,
    relatedSlugs: ["leather-key-cover-set"],
  },
  {
    id: "7",
    slug: "leather-key-cover-set",
    name: "Leather Key Cover Set",
    shortDescription: "Premium leather key fob protection",
    description: "Protect and style your car key with genuine leather.",
    category: "mobile-holders",
    basePrice: 850,
    images: [
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&q=80",
    ],
    badge: "Limited Stock",
    isSeatCover: false,
    isFeatured: true,
    inStock: true,
    relatedSlugs: ["universal-mobile-holder"],
  },
  {
    id: "8",
    slug: "seat-cover-floor-mat-combo",
    name: "Seat Cover + Floor Mat Combo",
    shortDescription: "Complete interior upgrade bundle — save 15%",
    description: "Premium seat covers paired with 7D floor mats at a special bundle price.",
    category: "combo-deals",
    basePrice: 17500,
    images: [
      "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80",
    ],
    badge: "Best Seller",
    isSeatCover: true,
    isFeatured: true,
    inStock: true,
    relatedSlugs: ["premium-leather-seat-covers", "7d-floor-mats-premium"],
  },
  {
    id: "9",
    slug: "fog-lights-led",
    name: "LED Fog Lights Pair",
    shortDescription: "High-intensity fog lights for all weather",
    description: "Premium LED fog lights with sharp cut-off pattern.",
    category: "led-lights",
    basePrice: 5500,
    images: ["https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80"],
    isSeatCover: false,
    isFeatured: false,
    inStock: true,
    relatedSlugs: ["led-headlight-projector"],
  },
  {
    id: "10",
    slug: "mud-flaps-set",
    name: "Heavy Duty Mud Flaps",
    shortDescription: "Protect your car body from road debris",
    description: "Durable mud flaps designed for Pakistani road conditions.",
    category: "exterior-accessories",
    basePrice: 1800,
    images: ["https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80"],
    isSeatCover: false,
    isFeatured: false,
    inStock: true,
    relatedSlugs: ["7d-floor-mats-premium"],
  },
];

export function seedInventory(): InventoryCatalog {
  return {
    version: 1,
    updatedAt: new Date().toISOString(),
    products: PRODUCTS,
    categories: [
      { slug: "seat-covers", name: "Seat Covers", description: "Custom-fit premium leather & scratchless covers", image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&q=80", isHero: true },
      { slug: "led-lights", name: "LED & Projector Lights", description: "Headlights, fog lights & ambient lighting", image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=600&q=80", isHero: false },
      { slug: "floor-mats", name: "Floor & TP Mats", description: "7D mats, simple mats & full protection TP mats", image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&q=80", isHero: false },
      { slug: "exterior-accessories", name: "Exterior Accessories", description: "Mud flaps, air press & body styling", image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&q=80", isHero: false },
      { slug: "mobile-holders", name: "Mobile Holders & Key Covers", description: "Dashboard holders & premium key covers", image: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=600&q=80", isHero: false },
      { slug: "combo-deals", name: "Combo Deals", description: "Bundle & save on complete car upgrades", image: "https://images.unsplash.com/photo-1542362567-b07e54358753?w=600&q=80", isHero: false },
    ],
    carMakes: ["Toyota", "Honda", "Suzuki", "Kia", "Hyundai", "MG", "Changan", "Proton"],
    carModels: [
      { make: "Toyota", model: "Corolla", priceMultiplier: 1 },
      { make: "Toyota", model: "Yaris", priceMultiplier: 0.92 },
      { make: "Toyota", model: "Fortuner", priceMultiplier: 1.25 },
      { make: "Toyota", model: "Hilux", priceMultiplier: 1.2 },
      { make: "Toyota", model: "Prado", priceMultiplier: 1.35 },
      { make: "Honda", model: "Civic", priceMultiplier: 1.05 },
      { make: "Honda", model: "City", priceMultiplier: 0.95 },
      { make: "Honda", model: "BR-V", priceMultiplier: 1 },
      { make: "Suzuki", model: "Alto", priceMultiplier: 0.85 },
      { make: "Suzuki", model: "Cultus", priceMultiplier: 0.9 },
      { make: "Suzuki", model: "Swift", priceMultiplier: 0.93 },
      { make: "Kia", model: "Sportage", priceMultiplier: 1.1 },
      { make: "Kia", model: "Picanto", priceMultiplier: 0.88 },
      { make: "Hyundai", model: "Tucson", priceMultiplier: 1.12 },
      { make: "MG", model: "HS", priceMultiplier: 1.05 },
      { make: "Changan", model: "Alsvin", priceMultiplier: 0.95 },
      { make: "Proton", model: "Saga", priceMultiplier: 0.9 },
    ],
    years: ["2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015"],
    seatCoverQualities: [
      { id: "LR9", label: "LR9", description: "Economy Leather Rite", basePrice: 12000 },
      { id: "ST8", label: "ST8", description: "Standard Leather Rite", basePrice: 15000 },
      { id: "ST27", label: "ST27", description: "Premium Leather Rite", basePrice: 18500 },
      { id: "NS3", label: "NS3", description: "Advanced Leather Rite", basePrice: 22000 },
      { id: "Japanese Scratchless", label: "Japanese", description: "Japanese Scratchless Material", basePrice: 25000 },
      { id: "Scratchless Premium", label: "Premium", description: "Scratchless Premium Material", basePrice: 28000 },
    ],
    coverColors: [
      { color: "Black", surcharge: 0 },
      { color: "Grey", surcharge: 0 },
      { color: "Beige", surcharge: 0 },
      { color: "Brown", surcharge: 0 },
      { color: "Mustard", surcharge: 500 },
      { color: "Maroon", surcharge: 500 },
    ],
  };
}
